-- MySQL Script generated by MySQL Workbench
-- mié 06 nov 2019 13:25:27 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVERO` (
  `Coordenadas` INT NOT NULL,
  `Localizacion` VARCHAR(45) NULL,
  PRIMARY KEY (`Coordenadas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Coordenadas` INT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `Coordenadas_idx` (`Coordenadas` ASC),
  CONSTRAINT `Coordenadas`
    FOREIGN KEY (`Coordenadas`)
    REFERENCES `mydb`.`VIVERO` (`Coordenadas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `Codigo` INT NOT NULL,
  `Stock` INT NULL,
  `Precio` INT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UBICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UBICA` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Codigo` INT NOT NULL,
  `Coordenadas` INT NOT NULL,
  PRIMARY KEY (`Nombre`, `Codigo`, `Coordenadas`),
  INDEX `Codigo_idx` (`Codigo` ASC),
  INDEX `Coordenadas_idx` (`Coordenadas` ASC),
  CONSTRAINT `Nombre`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`ZONA` (`Nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Codigo`
    FOREIGN KEY (`Codigo`)
    REFERENCES `mydb`.`PRODUCTO` (`Codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Coordenadas`
    FOREIGN KEY (`Coordenadas`)
    REFERENCES `mydb`.`ZONA` (`Coordenadas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `dni` VARCHAR(45) NOT NULL,
  `Bonificacion` INT NULL,
  `Total_mensual` INT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `dni` VARCHAR(45) NOT NULL,
  `Sueldo` INT NULL,
  `css` INT NULL,
  `Antiguedad` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Coordenadas` INT NULL,
  PRIMARY KEY (`dni`),
  INDEX `Coordenadas_idx` (`Coordenadas` ASC),
  INDEX `Nombre_idx` (`Nombre` ASC),
  CONSTRAINT `Nombre`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`ZONA` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Coordenadas`
    FOREIGN KEY (`Coordenadas`)
    REFERENCES `mydb`.`ZONA` (`Coordenadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EM_CLI_PRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EM_CLI_PRO` (
  `dni_cli` VARCHAR(45) NOT NULL,
  `Codigo` INT NOT NULL,
  `Cantidad` INT NULL,
  `Fecha` DATE NOT NULL,
  `dni_em` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni_cli`, `Codigo`, `Fecha`, `dni_em`),
  INDEX `Codigo_idx` (`Codigo` ASC),
  INDEX `dni_em_idx` (`dni_em` ASC),
  CONSTRAINT `dni_cli`
    FOREIGN KEY (`dni_cli`)
    REFERENCES `mydb`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `dni_em`
    FOREIGN KEY (`dni_em`)
    REFERENCES `mydb`.`EMPLEADO` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `Codigo`
    FOREIGN KEY (`Codigo`)
    REFERENCES `mydb`.`PRODUCTO` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
